### ISSUE TITLE
Add option to display "No data" if no images?

### ISSUE THREAD

**Issue by dazzatronic** [Dalvany/dalvany-image-panel#68]
Hi
I'm using your image panel to display 'problem' images and it works fine if there are images to be displayed.  But if there are no images, the panel gives an error message. 

Can there be an option to display "No data" (like on other Grafana panels) when there are no images?
Thanks

**Comment by Dalvany** [comment]
Hello @dazzatronic, thanks for using the plugin and reporting an issue !
I'll see if I can do something and let you know, don't expect it too soon though

**Comment by Dalvany** [comment]
@dazzatronic I made some change, now when the query return no data point, a consistent message `No data` is displayed.

Can you test this pre-release and let me know if it's ok ?

**Comment by Dalvany** [comment]
Hello @dazzatronic don't worry for the late response, it's ok.
I'm surprise that you still have this message, perhaps something wrong with the release or when you installed it because according to [this diff](https://github.com/Dalvany/dalvany-image-panel/commit/41d06ce8346d7be0befb81c27df8c591297e85f0#diff-5e4db54b6c0f33a7330fd0031d7b2654feac887a6bb57a667e50de2682ca5087R118) the error you got is nowhere in the code now.
I'll check the pre-release to see if something went wrong.

**Comment by Dalvany** [comment]
Ok, found it [here](https://github.com/Dalvany/dalvany-image-panel/blob/main/src/DynamicImagePanel.tsx#L336) I'll make the changes.

**Comment by Dalvany** [comment]
It should be fine now, can redownload and retest the [pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.8.0) ?

**Comment by Dalvany** [comment]
Nice, I will make a proper release to grafana then. Thank you for your feed back !
