### ISSUE TITLE
cant delete Baseurl 

### ISSUE THREAD

**Issue by corgan2222** [Dalvany/dalvany-image-panel#9]
Hello, thanks for the plugin! 
I have the problem, that i have the full path stored in the database, not only the filename. And the path can be different on each image. atm i cant delete the basepath and suffix. Its magicly come back all the time. 
Is this a bug, or be intended?
It would be great to just show the fullpath from the Database.

Thanks

**Comment by Dalvany** [comment]
HI @corgan2222, thanks for the feed back, I'll try to make the base URL optional.

**Comment by Dalvany** [comment]
Hi @corgan2222 , I made the changes and tried it manually. Do you think you can try [this release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.2.0) and confirm it works with your data before I push it to grafana ?

**Comment by corgan2222** [comment]
wow, thanks for this quick fix! This works great!! Thanks a lot!

**Comment by corgan2222** [comment]
One last question. 

Im loading the image path from a influxDB. If there are multiple images in the selected timerange, then your plugin shows all images. 
Sadly select distinct(image) seams not working in influx on a string field.
Any change that you could add something like an option, to show an image only once?

**Comment by Dalvany** [comment]
Could provide the query ? Do you use a `group by` clause ? `distinct` without a `group by` clause seems to work for me.

Here without distinct and no group by (I just diplay the alternate text instead of image on purpose because with my data two different values could lead to the same picture)
![without_distinct](https://user-images.githubusercontent.com/9901407/90672234-1bd17c80-e256-11ea-9869-b56dd4e48068.png)

Here with distinct and no group by
![with_distinct](https://user-images.githubusercontent.com/9901407/90672382-59cea080-e256-11ea-9091-59c4d25b627e.png)

Here with distinct and group by interval
![group_by](https://user-images.githubusercontent.com/9901407/90673238-baaaa880-e257-11ea-9e6c-9f6289aa9e80.png)

**Comment by Dalvany** [comment]
Or perhaps you want to 'reduce' consecutive equals values into a single one ? In my capture something that display :
```
10d 04n 03n 04n 03n 11n ...
```
