### ISSUE TITLE
Image Auto Fitting the Panel

### ISSUE THREAD

**Issue by maxbaiw29** [Dalvany/dalvany-image-panel#96]
Dear Sir/Madam,

Would it be possible to add a feature that automatically adjusts the size of pictures to fit the entire panel when displaying multiple images? Currently, I have to manually adjust the height and size for each device with different dimensions. I appreciate your efforts and thank you for your work.

Best regards,
Max

**Comment by Dalvany** [comment]
Hi @maxbaiw29,
Thanks for using the plugin.

I'll see what I can come up with but it might take time.

**Comment by maxbaiw29** [comment]
Hi @Dalvany, thanks for your response.

**Comment by Dalvany** [comment]
Just to be sure I understand what you need : you want images to be on a single line ?

**Comment by maxbaiw29** [comment]
Both if possible. Thank you

**Comment by Dalvany** [comment]
Hi @maxbaiw29, I made a ["pre-release"](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v4.0.0).
It adds a switch button in configuration that enables an "auto fit" feature. It's disable by default so that I'm sure it won't break any dashboard for anyone.
Can you try it to see if it's what you needed ?
